# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Smudgetools < Formula
  desc "Tools for my work with smudge comics"
  homepage "https://github.com/dbarbuzzi/smudgetools"
  version "1.2.1"

  if OS.mac?
    url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.2.1/smudgetools_1.2.1_macOS_64bit.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f62e49da50f30cd94c3c8235da73957ff444aef3f714cfcb843480b3150858e2"
  elsif OS.linux?
    url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.2.1/smudgetools_1.2.1_Linux_64bit.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "1234e1970b7dc0e76bd819a3fbd129819a8a6cadb8ff865dc4a9ee81afa4cdfd"
  end

  def install
    bin.install "smudge"
  end

  test do
    system "#{bin}/smudge --version"
  end
end
