# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Smudgetools < Formula
  desc "Tools for my work with smudge comics"
  homepage "https://github.com/dbarbuzzi/smudgetools"
  version "1.3.0"

  on_macos do
    url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.3.0/smudgetools_1.3.0_macOS_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2ea099bbb60500021b9dacdb3b1f62b0659ff8e86013f1930e5441853e95f576"

    def install
      bin.install "smudge"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Smudgetools
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.3.0/smudgetools_1.3.0_Linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "12d62362cdb40d0e6d7477fc4388bec957cace77209be440f40f927211bc990b"

      def install
        bin.install "smudge"
      end
    end
  end

  test do
    system "#{bin}/smudge --version"
  end
end
