# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Smudgetools < Formula
  desc "Tools for my work with smudge comics"
  homepage "https://github.com/dbarbuzzi/smudgetools"
  version "1.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.2.2/smudgetools_1.2.2_macOS_64bit.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "0df5b127df826d75eb555d2966658de51e97c467c3148c36dfc5a4c9bc3bd6cc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dbarbuzzi/smudgetools/releases/download/v1.2.2/smudgetools_1.2.2_Linux_64bit.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "63188efadc0f65eaf64fbdc7ff6946c71b295fb25fb86a7eeb8c114604fb4b4c"
    end
  end

  def install
    bin.install "smudge"
  end

  test do
    system "#{bin}/smudge --version"
  end
end
