# This file was generated by GoReleaser. DO NOT EDIT.
class Tvd < Formula
  desc "Download Twitch VODs"
  homepage "https://github.com/dbarbuzzi/tvd"
  version "0.4.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dbarbuzzi/tvd/releases/download/v0.4.4/tvd_0.4.4_macOS_amd64.tar.gz"
    sha256 "ca341627d88d9c128281d65d0f3a6acc6b53d48cbe88fb802bc7c323f090b47c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dbarbuzzi/tvd/releases/download/v0.4.4/tvd_0.4.4_linux_amd64.tar.gz"
      sha256 "3563870db383af3bcf966a982790c2daf77c9bfec6b5421f087638173e0bfad1"
    end
  end

  def install
    bin.install "tvd"
  end

  test do
    system "#{bin}/tvd --version"
  end
end
