# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tvd < Formula
  desc "Download Twitch VODs"
  homepage "https://github.com/dbarbuzzi/tvd"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dbarbuzzi/tvd/releases/download/v0.5.0/tvd_0.5.0_macOS_amd64.tar.gz"
    sha256 "004a35989f76febbed70069a766097c11c6f24a826db0c8f5b19d25bee46e7f4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dbarbuzzi/tvd/releases/download/v0.5.0/tvd_0.5.0_linux_amd64.tar.gz"
    sha256 "6f8c332418469f6ba58acd144967cb3154a540b9689c61b5cae1fdc7182d435e"
  end

  def install
    bin.install "tvd"
  end

  test do
    system "#{bin}/tvd --version"
  end
end
